/*
 * generated by Xtext
 */
package org.xtext.example.pascal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PascalUiModule extends org.xtext.example.pascal.ui.AbstractPascalUiModule {
	public PascalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
